config/routes.rb
Rails.application.routes.draw do

  resources :persons

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def index
    @persons = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def create
    person = Person.create(person_params)
    if person.saves
      redirect_to person_path(person)
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(page_params)
      # Success
      redirect_to person_path(@person)
    else
      # Fail
      render :edit
    end
  end

  def destroy
    person = Person.find(params[:id])
    person.destroy
    redirect_to person_path
  end

  def new
    @person = Person.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonModel</title>
    <%= csrf_meta_tags %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/persons/index.html.erb
<h1>People</h1>
<%= link_to 'Add New Person', new_person_path %>
<hr />

<%= link_to 'View All People' person_path(person) %>

app/views/persons/new.html.erb
<h1>Add New Person</h1>

<%= form_for @person do |f| %>
<div>
  <%= f.label :name %>
  <%= f.text_field :name, placeholder: 'Name', required: true %>
</div>
<div>
  <%= f.label :age %>
  <%= f.text_field :age, placeholder 'Age', required: true %>
</div>
<div>
  <%= f.label :hair_color %>
  <%= f.text_field :hair_color, placeholder 'Hair Color', required: true %>
</div>
<div>
  <%= f.label :eye_color %>
  <%= f.text_field :eye_color, placeholder 'Eye Color', required: true %>
</div>
<div>
  <%= f.label :gender %>
  <%= f.text_field :gender, placeholder: 'Gender', required: true %>
</div>
<div>
  <%= f.label :alive %>
  <%= f.check_box :alive %>
</div>

  <%= f.submit %>

<% end %>

app/views/persons/show.html.erb
<h1>Persons#show</h1>
<p>Find me in app/views/persons/show.html.erb</p>